package br.com.lilweather.dto;

import br.com.lilweather.clima.Weather;

public record WeatherListDTO(
		Long id,
		String cityName,
		String cityCountry,
		double temp1,
		int humidity1,
		String weather1,
		String description1,
		String timer1,
		double temp2,
		int humidity2,
		String weather2,
		String description2,
		String timer2,
		double temp3,
		int humidity3,
		String weather3,
		String description3,
		String timer3,
		double temp4,
		int humidity4,
		String weather4,
		String description4,
		String timer4,
		double temp5,
		int humidity5,
		String weather5,
		String description5,
		String timer5,
		double temp6,
		int humidity6,
		String weather6,
		String description6,
		String timer6,
		double temp7,
		int humidity7,
		String weather7,
		String description7,
		String timer7,
		double temp8,
		int humidity8,
		String weather8,
		String description8,
		String timer8,
		double temp9,
		int humidity9,
		String weather9,
		String description9,
		String timer9

) {
	public WeatherListDTO(Weather weather) {
		this(weather.getId(),
				weather.getCityName(),
				weather.getCityCountry(),
				weather.getTemp1(),
				weather.getHumidity1(),
				weather.getWeather1(),
				weather.getDescription1(),
				weather.getTimer1(),
				weather.getTemp2(),
				weather.getHumidity2(),
				weather.getWeather2(),
				weather.getDescription2(),
				weather.getTimer2(),
				weather.getTemp3(),
				weather.getHumidity3(),
				weather.getWeather3(),
				weather.getDescription3(),
				weather.getTimer3(),
				weather.getTemp4(),
				weather.getHumidity4(),
				weather.getWeather4(),
				weather.getDescription4(),
				weather.getTimer4(),
				weather.getTemp5(),
				weather.getHumidity5(),
				weather.getWeather5(),
				weather.getDescription5(),
				weather.getTimer5(),
				weather.getTemp6(),
				weather.getHumidity6(),
				weather.getWeather6(),
				weather.getDescription6(),
				weather.getTimer6(),
				weather.getTemp7(),
				weather.getHumidity7(),
				weather.getWeather7(),
				weather.getDescription7(),
				weather.getTimer7(),
				weather.getTemp8(),
				weather.getHumidity8(),
				weather.getWeather8(),
				weather.getDescription8(),
				weather.getTimer8(),
				weather.getTemp9(),
				weather.getHumidity9(),
				weather.getWeather9(),
				weather.getDescription9(),
				weather.getTimer9());
	}
}
